version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo Installing source NPM packages...
      - pip install -r requirements.txt
  build:
    commands:
      - echo Building the Docker image...
      - docker build -t my-flask-app .
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - '**/*'
